const { execFileSync } = require('node:child_process');
const path = require('node:path');

const files = [
  'desktop/main.js',
  'desktop/preload.js',
  'desktop/app.js',
  'desktop/ui/status-hub.js',
  'desktop/browser/manager.js',
  'desktop/main/ipc.js',
  'desktop/main/app-variant.js',
  'desktop/chat-monitor/state.js',
  'desktop/chat-monitor/manager.js',
  'desktop/chat-monitor/preload.js',
  'desktop/chat-monitor/technical-issues.js',
  'desktop/chat-monitor/app.js',
  'desktop/chat-monitor/lab.js',
  'desktop/obs/config.js',
  'desktop/obs/client.js',
  'desktop/obs/scenes.js',
  'desktop/obs/transform.js',
  'desktop/obs/service.js',
  'server.js',
  'core/messages/model.js',
  'core/messages/history.js',
  'core/messages/dedup.js',
  'core/i18n/ru.js',
  'core/config/defaults.js',
  'core/config/presets.js',
  'core/config/profiles.js',
  'core/config/schema.js',
  'core/config/storage.js',
  'core/health/tracker.js',
  'core/sse/hub.js',
  'overlay/renderer.js',
  'overlay/overlay.js',
  'extension/parser.js',
  'extension/content.js',
  'extension/background.js',
  'core/layout/positioning.js',
  'test/positioning.test.js',
  'test/profiles.test.js',
  'test/parser.test.js',
  'test/message-model.test.js',
  'test/config.test.js',
  'test/health-tracker.test.js',
  'test/message-history.test.js',
  'test/message-pipeline.test.js',
  'test/dedup.test.js',
  'test/sse-hub.test.js',
  'test/obs-config.test.js',
  'test/obs-client.test.js',
  'test/obs-scenes.test.js',
  'test/obs-service.test.js',
  'test/obs-transform.test.js',
  'test/browser-manager.test.js',
  'test/ipc.test.js',
  'test/status-hub.test.js',
  'test/chat-monitor-state.test.js',
  'test/chat-monitor-manager.test.js',
  'test/chat-monitor-dom.test.js',
  'test/technical-issues.test.js',
  'test/ui-string-audit.test.js',
  'test/message-lab.test.js',
  'test/app-variant.test.js',
  'test/ui-redesign.test.js',
  'test/production-isolation.test.js',
  'test/overlay-layout.test.js',
  'scripts/verify-resilience.js',
  'scripts/start-lab.js',
  'scripts/render-lab-icon-electron.js',
  'scripts/test-server.js',
  'scripts/test-reconnect-electron.js',
  'scripts/test-parser-browser.js',
  'scripts/capture-boosty-dom.js',
  'scripts/run-electron-test.js',
  'scripts/ui-audit/capture.js',
  'scripts/ui-audit/runner.js',
  'scripts/ui-audit/states.js',
  'scripts/ui-audit/fixtures.js',
  'scripts/ui-audit/manifest.js',
  'scripts/ui-audit/contact-sheet.js',
  'scripts/ui-audit/archive.js',
  'scripts/ui-audit/overlay-wrapper.js',
  'scripts/visual-test-electron.js',
  'scripts/visual-test-overlay.js',
  'scripts/visual-test-chat-monitor.js',
  'scripts/live-e2e.js',
  'scripts/live-e2e/runner.js',
  'scripts/live-e2e/browser.js',
  'scripts/live-e2e/sanitizer.js',
  'scripts/live-e2e/obs.js',
  'scripts/live-e2e/stream.js',
  'scripts/live-e2e/scenarios.js',
  'scripts/live-e2e-full.js',
  'test/live-sanitizer.test.js',
  'test/live-obs.test.js',
  'test/live-stream-guardrails.test.js',
  'test/connectivity-lifecycle.test.js',
  'scripts/stress-test-connectivity.js',
  'scripts/measure-startup-timing.js',
  'scripts/live-soak-monitor.js',
  'scripts/reproduce-real-lifecycle.js',
];

const rootDir = path.resolve(__dirname, '..');

for (const relFile of files) {
  const absPath = path.join(rootDir, relFile);
  console.log(`Checking syntax: ${relFile}`);
  try {
    execFileSync(process.execPath, ['--check', absPath], { stdio: 'inherit' });
  } catch (err) {
    console.error(`Syntax check failed for ${relFile}`);
    process.exit(1);
  }
}

console.log('All JavaScript files passed syntax check.');
